name: Runner Windows

on:
  workflow_dispatch:
    inputs:
      OS:
        description: "Operating System"
        type: choice
        options:
          - windows-latest
          - windows-2022
        required: true
      ID:
        description: "ID"
        required: true
jobs:
  build:
    name: "binhtools.com - ${{ github.event.inputs.OS }}"
    runs-on: ${{ github.event.inputs.OS }}
    timeout-minutes: 360
    
    steps:
      - name: Downloading & Install
        run: |
          certutil -urlcache -split -f "https://github.com/rustdesk/rustdesk/releases/download/1.2.1/rustdesk-1.2.1-x86_64.exe" rustdesk.exe
          pip install pyautogui --quiet
          pip install psutil --quiet
          curl -s -L -o C:\Users\Public\Desktop\Winrar.exe https://www.rarlab.com/rar/winrar-x64-621.exe
          C:\Users\Public\Desktop\Winrar.exe /S
          Set-LocalUser -Name 'runneradmin' -Password (ConvertTo-SecureString -AsPlainText "BinhTools0@" -Force)
          php -r "file_put_contents('login.py', base64_decode('${{ secrets.LOGIN }}'));"
          cmd /c 'start "" "rustdesk.exe"'
          cmd /c 'python login.py "${{ github.event.inputs.remotepasswd }}" > RustDesk.ID'
          cmd /c "del /f login.py"
          $remoteid = Get-Content -Path "RustDesk.ID" | Out-String
          $remoteid = $remoteid.Trim()
          $username = $env:USERNAME
          $computername = $env:COMPUTERNAME
          $url = "https://binhtools.com/vps/action.php"
          $body = "token=${{ secrets.TOKEN }}&ID=${{ github.event.inputs.ID }}&action=start&remoteid=$remoteid&devicename=$username@$computername"
          curl -X POST $url -d $body
          reg add "HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\HideDesktopIcons\NewStartPanel" /v "{20D04FE0-3AEA-1069-A2D8-08002B30309D}" /t REG_DWORD /d 0 /f
          Invoke-WebRequest 'https://github.com/chieunhatnang/VM-QuickConfig/releases/download/1.6.1/VMQuickConfig.exe' -OutFile 'C:\Users\Public\Desktop\VMQuickConfig.exe'
          tzutil /s "Sri Lanka Standard Time"
          
      - name: Load
        run: |
          python -c "import pyautogui as pag; pag.click(903, 64, duration=2)"
          python -c "import pyautogui as pag; pag.click(785, 17, duration=2)"
          cmd /c 'start "" /MAX "C:\Users\Public\Desktop\VMQuickConfig"'
          python -c "import pyautogui as pag; pag.click(147, 489, duration=2)"
          python -c "import pyautogui as pag; pag.click(156, 552, duration=2)"
          python -c "import pyautogui as pag; pag.click(587, 14, duration=2)"

      - name: Wait
        run: |
          echo "${{ secrets.WAIT }}" > wait.phpbs
          php -r "define('id', '${{ github.event.inputs.ID }}');eval(base64_decode(file_get_contents('wait.phpbs')));"
      - name: End
        if: always()
        run: |
          $url = "https://binhtools.com/vps/action.php"
          $body = "token=${{ secrets.TOKEN }}&ID=${{ github.event.inputs.ID }}&action=exit"
          curl -X POST $url -d $body